export const States = [
  {value: '', text: '-Location-'},
  {value: 'Abia', text: 'Abia'},
  {value: 'Adamawa', text: 'Adamawa'},
  {value: 'Akwa Ibom', text: 'Akwa Ibom'},
  {value: 'Anambra', text: 'Anambra'},
  {value: 'Bauchi', text: 'Bauchi'},
  {value: 'Bayelsa', text: 'Bayelsa'},
  {value: 'Benue', text: 'Benue'},
  {value: 'Borno', text: 'Borno'},
  {value: 'Cross River', text: 'Cross River'},
  {value: 'Delta', text: 'Delta'},
  {value: 'Ebonyi', text: 'Ebonyi'},
  {value: 'Edo', text: 'Edo'},
  {value: 'Ekiti', text: 'Ekiti'},
  {value: 'Enugu', text: 'Enugu'},
  {value: 'Gombe', text: 'Gombe'},
  {value: 'Imo', text: 'Imo'},
  {value: 'Jigawa', text: 'Jigawa'},
  {value: 'Kaduna', text: 'Kaduna'},
  {value: 'Kano', text: 'Kano'},
  {value: 'Katsina', text: 'Katsina'},
  {value: 'Kebbi', text: 'Kebbi'},
  {value: 'Kogi', text: 'Kogi'},
  {value: 'Kwara', text: 'Kwara'},
  {value: 'Lagos', text: 'Lagos'},
  {value: 'Nasarawa', text: 'Nasarawa'},
  {value: 'Niger', text: 'Niger'},
  {value: 'Ogun', text: 'Ogun'},
  {value: 'Ondo', text: 'Ondo'},
  {value: 'Osun', text: 'Osun'},
  {value: 'Oyo', text: 'Oyo'},
  {value: 'Plateau', text: 'Plateau'},
  {value: 'Rivers', text: 'Rivers'},
  {value: 'Sokoto', text: 'Sokoto'},
  {value: 'Taraba', text: 'Taraba'},
  {value: 'Yobe', text: 'Yobe'},
  {value: 'Zamfara', text: 'Zamfara'},
  ];




export const Status = [
  {value: '', text: '-Status-'},
  {value: 'Undergraduate', text: 'Undergraduate'},
  {value: 'New Graduate', text: 'New Graduate'},
  {value: 'NYSC Corper', text: 'NYSC Corper'},
]


export const Schools = [
  {value: '', text: '-School Name-'},
  {value: 'Covenant University', text: 'Covenant University'},
  {value: 'Babcock University', text: 'Babcock University'},
  {value: 'University of Lagos', text: 'University of Lagos'},
  {value: 'Obafemi Awolowo University', text: 'Obafemi Awolowo University'},
  {value: 'University of Ibadan', text: 'University of Ibadan'},
  {value: 'University of Nigeria, Nsukka', text: 'University of Nigeria, Nsukka'},
  {value: 'Ahmadu Bello University', text: 'Ahmadu Bello University'},
  {value: 'University of Ilorin', text: 'University of Ilorin'},
  {value: 'University of Abuja', text: 'University of Abuja'},
  {value: 'Bells UNiversity Of Technology', text: 'Bells UNiversity Of Technology'},
  {value: 'Federal University of Technology, Minna', text: 'Federal University of Technology, Minna'},
  {value: 'University of Benin', text: 'University of Benin'},
  {value: 'Federal University of Technology, Akure', text: 'Federal University of Technology, Akure'},
  {value: 'University of Port Harcourt', text: 'University of Port Harcourt'},
  {value: 'Lagos State University', text: 'Lagos State University'},
  {value: 'Nnamdi Azikiwe University', text: 'Nnamdi Azikiwe University'},
  {value: 'Federal University of Agriculture, Abeokuta', text: 'Federal University of Agriculture, Abeokuta'},
  {value: 'University of Jos', text: 'University of Jos'},
  {value: 'University of Calabar', text: 'University of Calabar'},
  {value: 'Federal University of Technology, Owerri', text: 'Federal University of Technology, Owerri'},
  {value: 'University of Uyo', text: 'University of Uyo'},
  {value: 'Bayero University Kano', text: 'Bayero University Kano'},
  {value: 'Michael Okpara University of Agriculture, Umudike', text: 'Michael Okpara University of Agriculture, Umudike'},
  {value: 'Federal University, Oye Ekiti', text: 'Federal University, Oye Ekiti'},
  {value: 'University of Maiduguri', text: 'University of Maiduguri'},
  {value: 'Adekunle Ajasin University', text: 'Adekunle Ajasin University'},
  {value: 'University of Medical Sciences, Ondo', text: 'University of Medical Sciences, Ondo'},
  {value: 'Niger Delta University', text: 'Niger Delta University'},
  {value: 'American University of Nigeria', text: 'American University of Nigeria'},
  {value: 'Caleb University', text: 'Caleb University'},
  {value: 'Redeemers University', text: "Redeemer's University"},
  {value: 'Veritas University, Abuja', text: 'Veritas University, Abuja'},
  {value: 'Pan-Atlantic University', text: 'Pan-Atlantic University'},
  {value: 'Afe Babalola University', text: 'Afe Babalola University'},
  {value: 'Landmark University', text: 'Landmark University'},
  ];


  export const Course = [
    {value: '', text: '-Course Of Study-'},
    {value: 'Computer Science', text: 'Computer Science'},
    {value: 'Management Information Systems', text: 'Management Information Systems'},
    {value: 'Accounting', text: 'Accounting'},
    {value: 'Medicine', text: 'Medicine'},
    {value: 'Law', text: 'Law'},
    {value: 'Engineering', text: 'Engineering'},
    {value: 'Business Administration', text: 'Business Administration'},
    {value: 'Mass Communication', text: 'Mass Communication'},
    {value: 'Economics', text: 'Economics'},
    {value: 'Nursing', text: 'Nursing'},
    {value: 'Pharmacy', text: 'Pharmacy'},
    {value: 'Political Science', text: 'Political Science'},
    {value: 'Architecture', text: 'Architecture'},
    {value: 'Education', text: 'Education'},
    {value: 'Psychology', text: 'Psychology'},
    {value: 'Marketing', text: 'Marketing'},
    {value: 'Biochemistry', text: 'Biochemistry'},
    {value: 'Civil Engineering', text: 'Civil Engineering'},
    {value: 'International Relations', text: 'International Relations'},
    {value: 'Public Health', text: 'Public Health'},
    {value: 'History', text: 'History'},
    {value: 'Sociology', text: 'Sociology'},
    {value: 'Electrical/Electronic Engineering', text: 'Electrical/Electronic Engineering'},
    {value: 'Industrial Chemistry', text: 'Industrial Chemistry'},
    {value: 'Geology', text: 'Geology'},
    {value: 'Microbiology', text: 'Microbiology'},
    {value: 'Information Technology', text: 'Information Technology'},
    {value: 'Petroleum Engineering', text: 'Petroleum Engineering'},
    {value: 'Statistics', text: 'Statistics'},
    {value: 'Environmental Science', text: 'Environmental Science'},
    {value: 'Public Administration', text: 'Public Administration'},
    {value: 'International Business', text: 'International Business'},
    {value: 'Mechanical Engineering', text: 'Mechanical Engineering'},
    {value: 'Mathematics', text: 'Mathematics'},
    {value: 'Communication Arts', text: 'Communication Arts'},
    {value: 'Agricultural Science', text: 'Agricultural Science'},
    {value: 'Music', text: 'Music'},
    {value: 'Theater Arts', text: 'Theater Arts'},
    ];

    export const Profile = [
      {value: '', text: '-Profile-'},
      {value: 'Graphics Designer', text: 'Graphics Designer'},
      {value: 'Software Developer', text: 'Software Developer'},
      {value: 'Finance/Accounting', text: 'Finance/Accounting'},
      {value: 'Marketing', text: 'Marketing'},
      {value: 'Sales', text: 'Sales'},
      {value: 'Human Resources', text: 'Human Resources'},
      {value: 'Customer Service', text: 'Customer Service'},
      {value: 'Project Manager', text: 'Project Manager'},
      {value: 'Data Analyst', text: 'Data Analyst'},
      {value: 'Business Analyst', text: 'Business Analyst'},
      {value: 'Product Manager', text: 'Product Manager'},
      {value: 'Operations Manager', text: 'Operations Manager'},
      {value: 'Content Writer', text: 'Content Writer'},
      {value: 'Social Media Manager', text: 'Social Media Manager'},
      {value: 'Public Relations', text: 'Public Relations'},
      {value: 'Event Planner', text: 'Event Planner'},
      {value: 'Customer Success Manager', text: 'Customer Success Manager'},
      {value: 'Quality Assurance', text: 'Quality Assurance'},
      {value: 'IT Support', text: 'IT Support'},
      {value: 'Business Development', text: 'Business Development'},
      {value: 'Research Analyst', text: 'Research Analyst'},
      {value: 'Education/Training', text: 'Education/Training'},
      {value: 'Logistics/Supply Chain', text: 'Logistics/Supply Chain'},
      {value: 'Legal', text: 'Legal'},
      {value: 'Healthcare', text: 'Healthcare'},
      {value: 'Real Estate', text: 'Real Estate'},
      {value: 'Design/Architecture', text: 'Design/Architecture'},
      {value: 'Manufacturing/Production', text: 'Manufacturing/Production'},
      ];